<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.7.0.20230115" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.7.0.20230115" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.4" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta15" />
  </ItemGroup>

</Project>
