image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build
    - test

variables:
  NUGET_CONFIG_FILE: "nuget.config"  # 指定 nuget.config 檔案的路徑

build:
    stage: build
    script:
        - apt-get update && apt-get install -y nuget  # 使用 apt-get 在 Docker 容器中安裝 NuGet 工具
        - nuget restore -ConfigFile $NUGET_CONFIG_FILE
        - "dotnet build"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test"
