// <auto-generated />
using System;
using DBEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MySql.Migrations
{
    [DbContext(typeof(SealTypographicDbContext))]
    [Migration("20230301053957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountantGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountantGroupId");

                    b.ToTable("Accountants");
                });

            modelBuilder.Entity("DBEntities.AccountantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountantGroupNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccountantGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountantGroupNumber = "NO000",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            DeleteStatus = (byte)0,
                            Name = "預設群組",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        });
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroupJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountantId");

                    b.ToTable("AccountantSignGroupJournals");
                });

            modelBuilder.Entity("DBEntities.AccountantSignJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountantSignGroupJournalId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignGroupJournalId");

                    b.ToTable("AccountantSignJournals");
                });

            modelBuilder.Entity("DBEntities.AccountantSignLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountantSignJournalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<float>("Left")
                        .HasColumnType("float");

                    b.Property<float>("Top")
                        .HasColumnType("float");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("AccountantSignLocaltions");
                });

            modelBuilder.Entity("DBEntities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressArea")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressCity")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressLocate")
                        .HasColumnType("longtext");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("longtext");

                    b.Property<string>("BAN")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactName")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Fax")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("President")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortName")
                        .HasColumnType("longtext");

                    b.Property<string>("StockCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DBEntities.CustomerSealJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConfigType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerSealQuarterJournalId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSealQuarterJournalId");

                    b.ToTable("CustomerSealJournals");
                });

            modelBuilder.Entity("DBEntities.CustomerSealLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerSealJournalId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<float>("Left")
                        .HasColumnType("float");

                    b.Property<float>("Top")
                        .HasColumnType("float");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSealJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("CustomerSealLocaltions");
                });

            modelBuilder.Entity("DBEntities.CustomerSealQuarterJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime(6)");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerSealQuarterJournals");
                });

            modelBuilder.Entity("DBEntities.Letterhead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Letterheads");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LetterheadId")
                        .HasColumnType("int");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LetterheadId");

                    b.ToTable("LetterheadImageJournals");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<float>("Left")
                        .HasColumnType("float");

                    b.Property<int>("LetterheadImageJournalId")
                        .HasColumnType("int");

                    b.Property<float>("Top")
                        .HasColumnType("float");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LetterheadImageJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("LetterheadImageLocaltions");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<int>("TypographicPDFId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPDFId");

                    b.ToTable("TypographicPages");
                });

            modelBuilder.Entity("DBEntities.UploadFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("FileWorkStatus")
                        .HasColumnType("int");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("int");

                    b.Property<byte>("UploadType")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("UploadFiles");
                });

            modelBuilder.Entity("DBEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pwaosrsd")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.HasOne("DBEntities.AccountantGroup", "AccountantGroup")
                        .WithMany("Accountants")
                        .HasForeignKey("AccountantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantGroup");
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroupJournal", b =>
                {
                    b.HasOne("DBEntities.Accountant", "Accountant")
                        .WithMany("AccountantSignGroupJournals")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");
                });

            modelBuilder.Entity("DBEntities.AccountantSignJournal", b =>
                {
                    b.HasOne("DBEntities.AccountantSignGroupJournal", "AccountantSignGroupJournal")
                        .WithMany("AccountantSignJournals")
                        .HasForeignKey("AccountantSignGroupJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantSignGroupJournal");
                });

            modelBuilder.Entity("DBEntities.AccountantSignLocation", b =>
                {
                    b.HasOne("DBEntities.AccountantSignJournal", "AccountantSignJournal")
                        .WithMany()
                        .HasForeignKey("AccountantSignJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicPage", "TypographicPage")
                        .WithMany("AccountantSignLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantSignJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("DBEntities.CustomerSealJournal", b =>
                {
                    b.HasOne("DBEntities.CustomerSealQuarterJournal", "CustomerSealQuarterJournal")
                        .WithMany("CustomerSealJournals")
                        .HasForeignKey("CustomerSealQuarterJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerSealQuarterJournal");
                });

            modelBuilder.Entity("DBEntities.CustomerSealLocation", b =>
                {
                    b.HasOne("DBEntities.CustomerSealJournal", "CustomerSealJournal")
                        .WithMany()
                        .HasForeignKey("CustomerSealJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicPage", "TypographicPage")
                        .WithMany("CustomerSealLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerSealJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("DBEntities.CustomerSealQuarterJournal", b =>
                {
                    b.HasOne("DBEntities.Customer", "Customer")
                        .WithMany("CustomerSealQuarterJournals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageJournal", b =>
                {
                    b.HasOne("DBEntities.Letterhead", "Letterhead")
                        .WithMany("LetterheadImageJournals")
                        .HasForeignKey("LetterheadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Letterhead");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageLocation", b =>
                {
                    b.HasOne("DBEntities.LetterheadImageJournal", "LetterheadImageJournal")
                        .WithMany()
                        .HasForeignKey("LetterheadImageJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicPage", "TypographicPage")
                        .WithMany("LetterheadImageLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LetterheadImageJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.HasOne("DBEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.HasOne("DBEntities.TypographicPDF", "TypographicPDF")
                        .WithMany("TypographicPages")
                        .HasForeignKey("TypographicPDFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypographicPDF");
                });

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.Navigation("AccountantSignGroupJournals");
                });

            modelBuilder.Entity("DBEntities.AccountantGroup", b =>
                {
                    b.Navigation("Accountants");
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroupJournal", b =>
                {
                    b.Navigation("AccountantSignJournals");
                });

            modelBuilder.Entity("DBEntities.Customer", b =>
                {
                    b.Navigation("CustomerSealQuarterJournals");
                });

            modelBuilder.Entity("DBEntities.CustomerSealQuarterJournal", b =>
                {
                    b.Navigation("CustomerSealJournals");
                });

            modelBuilder.Entity("DBEntities.Letterhead", b =>
                {
                    b.Navigation("LetterheadImageJournals");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.Navigation("TypographicPages");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.Navigation("AccountantSignLocaltions");

                    b.Navigation("CustomerSealLocaltions");

                    b.Navigation("LetterheadImageLocaltions");
                });
#pragma warning restore 612, 618
        }
    }
}
