<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.Development.json" />
    <None Remove="appsettings.json" />
    <None Remove="DJLLocalAPI.cs.rej" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
	<ItemGroup>
	  <PackageReference Include="RestSharp" Version="110.2.0" />
	  <PackageReference Include="Serilog" Version="2.10.0" />
	  <PackageReference Include="Serilog.AspNetCore" Version="6.1.0" />
	  <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\DJLib\DJLib.csproj" />
	  <ProjectReference Include="..\DJScannerLib\DJScannerLib.csproj" />
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="Services\" />
	  <Folder Include="Properties\" />
	</ItemGroup>
	
</Project>