<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>    
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile></DocumentationFile>
    <IncrementVersionOnBuild>0.0.3.1+</IncrementVersionOnBuild>
    <Version>0.0.3.758</Version>
    <PackageIcon>android-chrome-128x128.png</PackageIcon>
    <Configurations>Debug;Release</Configurations>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>    
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="logs\**" />
    <Content Remove="logs\**" />
    <EmbeddedResource Remove="logs\**" />
    <None Remove="logs\**" />
  </ItemGroup>


  <ItemGroup>
    <None Include="..\..\SealTypographicWebAPI\wwwroot\swagger\android-chrome-128x128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="7.0.2" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="7.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="DJCommonLib" Version="6.0.4" />
    <PackageReference Include="DJImageLib" Version="1.0.1" />
    <PackageReference Include="DJKeycloakAPI" Version="6.0.7" />	
    <PackageReference Include="Keycloak.AuthServices.Authentication" Version="1.6.0" />
    <PackageReference Include="Keycloak.AuthServices.Authorization" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="6.0.25" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.25" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="2.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DBEntities\DBEntities.csproj" />
    <ProjectReference Include="..\DJSpire\DJSpire.csproj" />
    <ProjectReference Include="..\MySqlMigrations\MySql.csproj" />
    <ProjectReference Include="..\SqliteMigrations\Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Spire.Pdf">
      <HintPath>..\DJSpire\Library\Spire.Pdf.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Sit.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
