<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DJEncryption\DJEncryption.csproj" />
    <ProjectReference Include="..\DJLib\DJLib.csproj" />
    <ProjectReference Include="..\DJSharpZipLib\DJSharpZipLib.csproj" />
    <ProjectReference Include="..\TchznSeal\TchznSeal.csproj" />
  </ItemGroup>

</Project>