// <auto-generated />
using System;
using DBEntitiesExtension;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sqlite.Migrations.SealTypographicExtensionDb
{
    [DbContext(typeof(SealTypographicExtensionDbContext))]
    partial class SealTypographicExtensionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("DBEntitiesExtension.Accountant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantGroupId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Accountants");
                });

            modelBuilder.Entity("DBEntitiesExtension.AccountantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountantGroupNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("AccountantGroups");
                });

            modelBuilder.Entity("DBEntitiesExtension.AccountantSignGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantId");

                    b.ToTable("AccountantSignGroups");
                });

            modelBuilder.Entity("DBEntitiesExtension.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("DBEntitiesExtension.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLocate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DBEntitiesExtension.CustomerSealGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuarterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterId");

                    b.ToTable("CustomerSealGroups");
                });

            modelBuilder.Entity("DBEntitiesExtension.Letterhead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Letterheads");
                });

            modelBuilder.Entity("DBEntitiesExtension.Quarter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GregorianYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaiwanYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Quarters");
                });

            modelBuilder.Entity("DBEntitiesExtension.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageViewFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StackMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StackShift")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("DBEntitiesExtension.TemplateLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateLocations");
                });

            modelBuilder.Entity("DBEntitiesExtension.TemporarySealGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuarterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterId");

                    b.ToTable("TemporarySealGroups");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographicPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuarterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterId");

                    b.HasIndex("UploadFileId");

                    b.ToTable("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlankCheck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteCheck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAccountantCertificate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographicPDFId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPDFId");

                    b.ToTable("TypographicPages");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographicSealLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographyResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPageId");

                    b.HasIndex("TypographyResourceId");

                    b.ToTable("TypographicSealLocations");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographyResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountantSignGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerSealGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LetterheadId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSealType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemporarySealGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UploadFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignGroupId");

                    b.HasIndex("CustomerSealGroupId");

                    b.HasIndex("LetterheadId");

                    b.HasIndex("TemporarySealGroupId");

                    b.HasIndex("UploadFileId");

                    b.ToTable("TypographyResources");
                });

            modelBuilder.Entity("DBEntitiesExtension.UploadFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileWorkStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("UploadType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("UploadFiles");
                });

            modelBuilder.Entity("DBEntitiesExtension.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pwaosrsd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DBEntitiesExtension.Accountant", b =>
                {
                    b.HasOne("DBEntitiesExtension.AccountantGroup", "AccountantGroup")
                        .WithMany("Accountants")
                        .HasForeignKey("AccountantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntitiesExtension.Company", "Company")
                        .WithMany("Accountants")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantGroup");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntitiesExtension.AccountantGroup", b =>
                {
                    b.HasOne("DBEntitiesExtension.Company", "Company")
                        .WithMany("AccountantGroups")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntitiesExtension.AccountantSignGroup", b =>
                {
                    b.HasOne("DBEntitiesExtension.Accountant", "Accountant")
                        .WithMany("AccountantSignGroups")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");
                });

            modelBuilder.Entity("DBEntitiesExtension.Customer", b =>
                {
                    b.HasOne("DBEntitiesExtension.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntitiesExtension.CustomerSealGroup", b =>
                {
                    b.HasOne("DBEntitiesExtension.Customer", "Customer")
                        .WithMany("CustomerSealGroups")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntitiesExtension.Quarter", "Quarter")
                        .WithMany("CustomerSealGroups")
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Quarter");
                });

            modelBuilder.Entity("DBEntitiesExtension.Letterhead", b =>
                {
                    b.HasOne("DBEntitiesExtension.Company", "Company")
                        .WithMany("Letterheads")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntitiesExtension.Template", b =>
                {
                    b.HasOne("DBEntitiesExtension.Company", "Company")
                        .WithMany("Templates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntitiesExtension.TemplateLocation", b =>
                {
                    b.HasOne("DBEntitiesExtension.Template", "Template")
                        .WithMany("TemplateLocations")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DBEntitiesExtension.TemporarySealGroup", b =>
                {
                    b.HasOne("DBEntitiesExtension.Customer", "Customer")
                        .WithMany("TemporarySealGroups")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntitiesExtension.Quarter", "Quarter")
                        .WithMany("TemporarySealGroups")
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Quarter");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographicPDF", b =>
                {
                    b.HasOne("DBEntitiesExtension.Customer", "Customer")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntitiesExtension.Quarter", "Quarter")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("QuarterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntitiesExtension.UploadFile", "UploadFile")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("UploadFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Quarter");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographicPage", b =>
                {
                    b.HasOne("DBEntitiesExtension.TypographicPDF", "TypographicPDF")
                        .WithMany("TypographicPages")
                        .HasForeignKey("TypographicPDFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypographicPDF");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographicSealLocation", b =>
                {
                    b.HasOne("DBEntitiesExtension.TypographicPage", "TypographicPage")
                        .WithMany("TypographicSealLocations")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntitiesExtension.TypographyResource", "TypographyResource")
                        .WithMany("TypographicSealLocations")
                        .HasForeignKey("TypographyResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypographicPage");

                    b.Navigation("TypographyResource");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographyResource", b =>
                {
                    b.HasOne("DBEntitiesExtension.AccountantSignGroup", "AccountantSignGroup")
                        .WithMany("TypographyResources")
                        .HasForeignKey("AccountantSignGroupId");

                    b.HasOne("DBEntitiesExtension.CustomerSealGroup", "CustomerSealGroup")
                        .WithMany("TypographyResources")
                        .HasForeignKey("CustomerSealGroupId");

                    b.HasOne("DBEntitiesExtension.Letterhead", "Letterhead")
                        .WithMany("TypographyResources")
                        .HasForeignKey("LetterheadId");

                    b.HasOne("DBEntitiesExtension.TemporarySealGroup", "TemporarySealGroup")
                        .WithMany("TypographyResources")
                        .HasForeignKey("TemporarySealGroupId");

                    b.HasOne("DBEntitiesExtension.UploadFile", "UploadFile")
                        .WithMany("TypographyResources")
                        .HasForeignKey("UploadFileId");

                    b.Navigation("AccountantSignGroup");

                    b.Navigation("CustomerSealGroup");

                    b.Navigation("Letterhead");

                    b.Navigation("TemporarySealGroup");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("DBEntitiesExtension.UploadFile", b =>
                {
                    b.HasOne("DBEntitiesExtension.Company", "Company")
                        .WithMany("UploadFiles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntitiesExtension.User", b =>
                {
                    b.HasOne("DBEntitiesExtension.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntitiesExtension.Accountant", b =>
                {
                    b.Navigation("AccountantSignGroups");
                });

            modelBuilder.Entity("DBEntitiesExtension.AccountantGroup", b =>
                {
                    b.Navigation("Accountants");
                });

            modelBuilder.Entity("DBEntitiesExtension.AccountantSignGroup", b =>
                {
                    b.Navigation("TypographyResources");
                });

            modelBuilder.Entity("DBEntitiesExtension.Company", b =>
                {
                    b.Navigation("AccountantGroups");

                    b.Navigation("Accountants");

                    b.Navigation("Customers");

                    b.Navigation("Letterheads");

                    b.Navigation("Templates");

                    b.Navigation("UploadFiles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DBEntitiesExtension.Customer", b =>
                {
                    b.Navigation("CustomerSealGroups");

                    b.Navigation("TemporarySealGroups");

                    b.Navigation("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntitiesExtension.CustomerSealGroup", b =>
                {
                    b.Navigation("TypographyResources");
                });

            modelBuilder.Entity("DBEntitiesExtension.Letterhead", b =>
                {
                    b.Navigation("TypographyResources");
                });

            modelBuilder.Entity("DBEntitiesExtension.Quarter", b =>
                {
                    b.Navigation("CustomerSealGroups");

                    b.Navigation("TemporarySealGroups");

                    b.Navigation("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntitiesExtension.Template", b =>
                {
                    b.Navigation("TemplateLocations");
                });

            modelBuilder.Entity("DBEntitiesExtension.TemporarySealGroup", b =>
                {
                    b.Navigation("TypographyResources");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographicPDF", b =>
                {
                    b.Navigation("TypographicPages");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographicPage", b =>
                {
                    b.Navigation("TypographicSealLocations");
                });

            modelBuilder.Entity("DBEntitiesExtension.TypographyResource", b =>
                {
                    b.Navigation("TypographicSealLocations");
                });

            modelBuilder.Entity("DBEntitiesExtension.UploadFile", b =>
                {
                    b.Navigation("TypographicPDFs");

                    b.Navigation("TypographyResources");
                });
#pragma warning restore 612, 618
        }
    }
}
