// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealTypographicWebAPI.Entities;

#nullable disable

namespace SealTypographicWebAPI.Migrations
{
    [DbContext(typeof(SealTypographicDbContext))]
    [Migration("20221223082235_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Accountant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountantNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantGroupId");

                    b.ToTable("Accountants");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountantGroupNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccountantGroups");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SealMappingConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantId");

                    b.HasIndex("SealMappingConfigId");

                    b.ToTable("AccountantSignJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSingLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantSignJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("AccountantSingLocaltions");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCityArea")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLocate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SealMappingConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SealMappingConfigId");

                    b.ToTable("CustomerSealJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerSealJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSealJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("CustomerSealLocaltions");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Letterhead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LetterheadNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Letterheads");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.LetterheadImageJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LetterheadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SealMappingConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LetterheadId");

                    b.HasIndex("SealMappingConfigId");

                    b.ToTable("LetterheadImageJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.LetterheadImageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<int>("LetterheadImageJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LetterheadImageJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("LetterheadImageLocaltions");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.SealMappingConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubId")
                        .IsUnique();

                    b.ToTable("SealMappingConfigs");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographicPDFId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPDFId");

                    b.ToTable("TypographicPages");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GroupCreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TypographicPDFs");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pwaosrsd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Accountant", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.AccountantGroup", "AccountantGroup")
                        .WithMany("Accountants")
                        .HasForeignKey("AccountantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantGroup");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.Accountant", "Accountant")
                        .WithMany("AccountantSignJournals")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.SealMappingConfig", "SealMappingConfig")
                        .WithMany("AccountantSignJournals")
                        .HasForeignKey("SealMappingConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");

                    b.Navigation("SealMappingConfig");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSingLocation", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.AccountantSignJournal", "AccountantSignJournal")
                        .WithMany()
                        .HasForeignKey("AccountantSignJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.TypographicPage", "TypographicPage")
                        .WithMany("AccountantSingLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantSignJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.Customer", "Customer")
                        .WithMany("CustomerSealJournals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.SealMappingConfig", "SealMappingConfig")
                        .WithMany("CustomerSealJournals")
                        .HasForeignKey("SealMappingConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SealMappingConfig");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealLocation", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.CustomerSealJournal", "CustomerSealJournal")
                        .WithMany()
                        .HasForeignKey("CustomerSealJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.TypographicPage", "TypographicPage")
                        .WithMany("CustomerSealLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerSealJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.LetterheadImageJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.Letterhead", "Letterhead")
                        .WithMany("LetterheadImageJournals")
                        .HasForeignKey("LetterheadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.SealMappingConfig", "SealMappingConfig")
                        .WithMany("LetterheadImageJournals")
                        .HasForeignKey("SealMappingConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Letterhead");

                    b.Navigation("SealMappingConfig");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.LetterheadImageLocation", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.LetterheadImageJournal", "LetterheadImageJournal")
                        .WithMany()
                        .HasForeignKey("LetterheadImageJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.TypographicPage", "TypographicPage")
                        .WithMany("LetterheadImageLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LetterheadImageJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPage", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.TypographicPDF", "TypographicPDF")
                        .WithMany("TypographicPages")
                        .HasForeignKey("TypographicPDFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypographicPDF");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPDF", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Accountant", b =>
                {
                    b.Navigation("AccountantSignJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantGroup", b =>
                {
                    b.Navigation("Accountants");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Customer", b =>
                {
                    b.Navigation("CustomerSealJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Letterhead", b =>
                {
                    b.Navigation("LetterheadImageJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.SealMappingConfig", b =>
                {
                    b.Navigation("AccountantSignJournals");

                    b.Navigation("CustomerSealJournals");

                    b.Navigation("LetterheadImageJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPage", b =>
                {
                    b.Navigation("AccountantSingLocaltions");

                    b.Navigation("CustomerSealLocaltions");

                    b.Navigation("LetterheadImageLocaltions");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPDF", b =>
                {
                    b.Navigation("TypographicPages");
                });
#pragma warning restore 612, 618
        }
    }
}
