// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealTypographicWebAPI.DbModels;

#nullable disable

namespace SealTypographicWebAPI.Migrations
{
    [DbContext(typeof(SealTypographicDbContext))]
    [Migration("20221122012255_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.Accountant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountantGroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantGroupId");

                    b.ToTable("Accountants");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.AccountantGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountantGroups");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.AccountantSignJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountantId");

                    b.HasIndex("ImageGroupId");

                    b.ToTable("AccountantSignJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.CustomerSealJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("No")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stauts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ImageGroupId");

                    b.ToTable("CustomerSealJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.ImageGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImageGroups");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.Letterhead", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Letterheads");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.LetterheadImageJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LetterheadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("No")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImageGroupId");

                    b.HasIndex("LetterheadId");

                    b.ToTable("LetterheadImageJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.Accountant", b =>
                {
                    b.HasOne("SealTypographicWebAPI.DbModels.AccountantGroup", "AccountantGroup")
                        .WithMany("Accountants")
                        .HasForeignKey("AccountantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantGroup");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.AccountantSignJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.DbModels.Accountant", "Accountant")
                        .WithMany()
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.DbModels.ImageGroup", "ImageGroup")
                        .WithMany("AccountantSignJournals")
                        .HasForeignKey("ImageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");

                    b.Navigation("ImageGroup");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.CustomerSealJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.DbModels.Customer", "Customer")
                        .WithMany("CustomerSealJournals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.DbModels.ImageGroup", "ImageGroup")
                        .WithMany("CustomerSealJournals")
                        .HasForeignKey("ImageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ImageGroup");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.LetterheadImageJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.DbModels.ImageGroup", "ImageGroup")
                        .WithMany("LetterheadImageJournals")
                        .HasForeignKey("ImageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.DbModels.Letterhead", "Letterhead")
                        .WithMany()
                        .HasForeignKey("LetterheadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageGroup");

                    b.Navigation("Letterhead");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.AccountantGroup", b =>
                {
                    b.Navigation("Accountants");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.Customer", b =>
                {
                    b.Navigation("CustomerSealJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.DbModels.ImageGroup", b =>
                {
                    b.Navigation("AccountantSignJournals");

                    b.Navigation("CustomerSealJournals");

                    b.Navigation("LetterheadImageJournals");
                });
#pragma warning restore 612, 618
        }
    }
}
