// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SealTypographicWebAPI.Entities;

#nullable disable

namespace SealTypographicWebAPI.Migrations
{
    [DbContext(typeof(SealTypographicDbContext))]
    [Migration("20230118160534_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Accountant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantGroupId");

                    b.ToTable("Accountants");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountantGroupNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccountantGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountantGroupNumber = "NO000",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateUserId = 0,
                            DeleteStatus = (byte)0,
                            Name = "無群組",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateUserId = 0
                        });
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignCreateDateJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantId");

                    b.ToTable("AccountantSignCreateDateJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantSignCreateDateJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignCreateDateJournalId");

                    b.ToTable("AccountantSignJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantSignJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("AccountantSignLocaltions");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLocate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerSealQuarterJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSealQuarterJournalId");

                    b.ToTable("CustomerSealJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerSealJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSealJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("CustomerSealLocaltions");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealQuarterJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerSealQuarterJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Letterhead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Letterheads");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.LetterheadImageJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LetterheadId")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LetterheadId");

                    b.ToTable("LetterheadImageJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.LetterheadImageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<int>("LetterheadImageJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LetterheadImageJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("LetterheadImageLocaltions");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographicPDFId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPDFId");

                    b.ToTable("TypographicPages");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TypographicPDFs");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pwaosrsd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Accountant", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.AccountantGroup", "AccountantGroup")
                        .WithMany("Accountants")
                        .HasForeignKey("AccountantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantGroup");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignCreateDateJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.Accountant", "Accountant")
                        .WithMany("AccountantSignCreateDateJournals")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.AccountantSignCreateDateJournal", "AccountantSignCreateDateJournal")
                        .WithMany("AccountantSignJournals")
                        .HasForeignKey("AccountantSignCreateDateJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantSignCreateDateJournal");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignLocation", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.AccountantSignJournal", "AccountantSignJournal")
                        .WithMany()
                        .HasForeignKey("AccountantSignJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.TypographicPage", "TypographicPage")
                        .WithMany("AccountantSignLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantSignJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.CustomerSealQuarterJournal", "CustomerSealQuarterJournal")
                        .WithMany("CustomerSealJournals")
                        .HasForeignKey("CustomerSealQuarterJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerSealQuarterJournal");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealLocation", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.CustomerSealJournal", "CustomerSealJournal")
                        .WithMany()
                        .HasForeignKey("CustomerSealJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.TypographicPage", "TypographicPage")
                        .WithMany("CustomerSealLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerSealJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealQuarterJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.Customer", "Customer")
                        .WithMany("CustomerSealQuarterJournals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.LetterheadImageJournal", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.Letterhead", "Letterhead")
                        .WithMany("LetterheadImageJournals")
                        .HasForeignKey("LetterheadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Letterhead");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.LetterheadImageLocation", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.LetterheadImageJournal", "LetterheadImageJournal")
                        .WithMany()
                        .HasForeignKey("LetterheadImageJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SealTypographicWebAPI.Entities.TypographicPage", "TypographicPage")
                        .WithMany("LetterheadImageLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LetterheadImageJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPage", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.TypographicPDF", "TypographicPDF")
                        .WithMany("TypographicPages")
                        .HasForeignKey("TypographicPDFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypographicPDF");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPDF", b =>
                {
                    b.HasOne("SealTypographicWebAPI.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Accountant", b =>
                {
                    b.Navigation("AccountantSignCreateDateJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantGroup", b =>
                {
                    b.Navigation("Accountants");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.AccountantSignCreateDateJournal", b =>
                {
                    b.Navigation("AccountantSignJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Customer", b =>
                {
                    b.Navigation("CustomerSealQuarterJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.CustomerSealQuarterJournal", b =>
                {
                    b.Navigation("CustomerSealJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.Letterhead", b =>
                {
                    b.Navigation("LetterheadImageJournals");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPage", b =>
                {
                    b.Navigation("AccountantSignLocaltions");

                    b.Navigation("CustomerSealLocaltions");

                    b.Navigation("LetterheadImageLocaltions");
                });

            modelBuilder.Entity("SealTypographicWebAPI.Entities.TypographicPDF", b =>
                {
                    b.Navigation("TypographicPages");
                });
#pragma warning restore 612, 618
        }
    }
}
