// <auto-generated />
using System;
using DBEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sqlite.Migrations
{
    [DbContext(typeof(SealTypographicDbContext))]
    [Migration("20231031095756_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Accountants");
                });

            modelBuilder.Entity("DBEntities.AccountantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("AccountantGroups");
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantId");

                    b.ToTable("AccountantSignGroups");
                });

            modelBuilder.Entity("DBEntities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLocate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("DBEntities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLocate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DBEntities.CustomerSealGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuarterYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("TypographyType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterYearId");

                    b.ToTable("CustomerSealGroups");
                });

            modelBuilder.Entity("DBEntities.GroupAccountant", b =>
                {
                    b.Property<int>("AccountantGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountantGroupId", "AccountantId");

                    b.HasIndex("AccountantId");

                    b.ToTable("GroupAccountants");
                });

            modelBuilder.Entity("DBEntities.ImageCaptureLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageCaptureSettingId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSealType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImageCaptureSettingId");

                    b.ToTable("ImageCaptureLocations");
                });

            modelBuilder.Entity("DBEntities.ImageCaptureSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("ImageCaptureSettings");
                });

            modelBuilder.Entity("DBEntities.Letterhead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Letterheads");
                });

            modelBuilder.Entity("DBEntities.QuarterYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GregorianYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QuarterYears");
                });

            modelBuilder.Entity("DBEntities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageViewFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StackMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StackShift")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("DBEntities.TemplateLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateLocations");
                });

            modelBuilder.Entity("DBEntities.TemporarySealGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuarterYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterYearId");

                    b.ToTable("TemporarySealGroups");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuarterYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("TypographyType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterYearId");

                    b.HasIndex("UploadFileId");

                    b.ToTable("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlankCheck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteCheck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographicPDFId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UploadFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPDFId");

                    b.HasIndex("UploadFileId");

                    b.ToTable("TypographicPages");
                });

            modelBuilder.Entity("DBEntities.TypographicResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountantSignGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerSealGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LetterheadId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSealType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemporarySealGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UploadFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignGroupId");

                    b.HasIndex("CustomerSealGroupId");

                    b.HasIndex("LetterheadId");

                    b.HasIndex("TemporarySealGroupId");

                    b.HasIndex("UploadFileId");

                    b.ToTable("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.TypographicResourceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Angle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInpaint")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<byte>("SealDyeing")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographicResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPageId");

                    b.HasIndex("TypographicResourceId");

                    b.ToTable("TypographicResourceLocations");
                });

            modelBuilder.Entity("DBEntities.UploadFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileWorkStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("UploadType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("UploadFiles");
                });

            modelBuilder.Entity("DBEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeycloakUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Accountants")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.AccountantGroup", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("AccountantGroups")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroup", b =>
                {
                    b.HasOne("DBEntities.Accountant", "Accountant")
                        .WithMany("AccountantSignGroups")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");
                });

            modelBuilder.Entity("DBEntities.Customer", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.CustomerSealGroup", b =>
                {
                    b.HasOne("DBEntities.Customer", "Customer")
                        .WithMany("CustomerSealGroups")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.QuarterYear", "QuarterYear")
                        .WithMany("CustomerSealGroups")
                        .HasForeignKey("QuarterYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("QuarterYear");
                });

            modelBuilder.Entity("DBEntities.GroupAccountant", b =>
                {
                    b.HasOne("DBEntities.AccountantGroup", "AccountantGroup")
                        .WithMany("GroupAccountants")
                        .HasForeignKey("AccountantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Accountant", "Accountant")
                        .WithMany("GroupAccountants")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");

                    b.Navigation("AccountantGroup");
                });

            modelBuilder.Entity("DBEntities.ImageCaptureLocation", b =>
                {
                    b.HasOne("DBEntities.ImageCaptureSetting", "ImageCaptureSetting")
                        .WithMany("ImageCaptureLocations")
                        .HasForeignKey("ImageCaptureSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageCaptureSetting");
                });

            modelBuilder.Entity("DBEntities.ImageCaptureSetting", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("ImageCaptureSettings")
                        .HasForeignKey("CompanyId");

                    b.HasOne("DBEntities.User", "User")
                        .WithMany("ImageCaptureSettings")
                        .HasForeignKey("UserId");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBEntities.Letterhead", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Letterheads")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.Template", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Templates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.TemplateLocation", b =>
                {
                    b.HasOne("DBEntities.Template", "Template")
                        .WithMany("TemplateLocations")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DBEntities.TemporarySealGroup", b =>
                {
                    b.HasOne("DBEntities.Customer", "Customer")
                        .WithMany("TemporarySealGroups")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.QuarterYear", "QuarterYear")
                        .WithMany("TemporarySealGroups")
                        .HasForeignKey("QuarterYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("QuarterYear");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.HasOne("DBEntities.Customer", "Customer")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.QuarterYear", "QuarterYear")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("QuarterYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.UploadFile", "UploadFile")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("UploadFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("QuarterYear");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.HasOne("DBEntities.TypographicPDF", "TypographicPDF")
                        .WithMany("TypographicPages")
                        .HasForeignKey("TypographicPDFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.UploadFile", "UploadFile")
                        .WithMany()
                        .HasForeignKey("UploadFileId");

                    b.Navigation("TypographicPDF");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("DBEntities.TypographicResource", b =>
                {
                    b.HasOne("DBEntities.AccountantSignGroup", "AccountantSignGroup")
                        .WithMany("TypographicResources")
                        .HasForeignKey("AccountantSignGroupId");

                    b.HasOne("DBEntities.CustomerSealGroup", "CustomerSealGroup")
                        .WithMany("TypographicResources")
                        .HasForeignKey("CustomerSealGroupId");

                    b.HasOne("DBEntities.Letterhead", "Letterhead")
                        .WithMany("TypographicResources")
                        .HasForeignKey("LetterheadId");

                    b.HasOne("DBEntities.TemporarySealGroup", "TemporarySealGroup")
                        .WithMany("TypographicResources")
                        .HasForeignKey("TemporarySealGroupId");

                    b.HasOne("DBEntities.UploadFile", "UploadFile")
                        .WithMany("TypographicResources")
                        .HasForeignKey("UploadFileId");

                    b.Navigation("AccountantSignGroup");

                    b.Navigation("CustomerSealGroup");

                    b.Navigation("Letterhead");

                    b.Navigation("TemporarySealGroup");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("DBEntities.TypographicResourceLocation", b =>
                {
                    b.HasOne("DBEntities.TypographicPage", "TypographicPage")
                        .WithMany("TypographicResourceLocations")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicResource", "TypographicResource")
                        .WithMany("TypographicResourceLocations")
                        .HasForeignKey("TypographicResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypographicPage");

                    b.Navigation("TypographicResource");
                });

            modelBuilder.Entity("DBEntities.UploadFile", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("UploadFiles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.User", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.Navigation("AccountantSignGroups");

                    b.Navigation("GroupAccountants");
                });

            modelBuilder.Entity("DBEntities.AccountantGroup", b =>
                {
                    b.Navigation("GroupAccountants");
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroup", b =>
                {
                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.Company", b =>
                {
                    b.Navigation("AccountantGroups");

                    b.Navigation("Accountants");

                    b.Navigation("Customers");

                    b.Navigation("ImageCaptureSettings");

                    b.Navigation("Letterheads");

                    b.Navigation("Templates");

                    b.Navigation("UploadFiles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DBEntities.Customer", b =>
                {
                    b.Navigation("CustomerSealGroups");

                    b.Navigation("TemporarySealGroups");

                    b.Navigation("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntities.CustomerSealGroup", b =>
                {
                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.ImageCaptureSetting", b =>
                {
                    b.Navigation("ImageCaptureLocations");
                });

            modelBuilder.Entity("DBEntities.Letterhead", b =>
                {
                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.QuarterYear", b =>
                {
                    b.Navigation("CustomerSealGroups");

                    b.Navigation("TemporarySealGroups");

                    b.Navigation("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntities.Template", b =>
                {
                    b.Navigation("TemplateLocations");
                });

            modelBuilder.Entity("DBEntities.TemporarySealGroup", b =>
                {
                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.Navigation("TypographicPages");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.Navigation("TypographicResourceLocations");
                });

            modelBuilder.Entity("DBEntities.TypographicResource", b =>
                {
                    b.Navigation("TypographicResourceLocations");
                });

            modelBuilder.Entity("DBEntities.UploadFile", b =>
                {
                    b.Navigation("TypographicPDFs");

                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.User", b =>
                {
                    b.Navigation("ImageCaptureSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
