// <auto-generated />
using System;
using DBEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sqlite.Migrations
{
    [DbContext(typeof(SealTypographicDbContext))]
    [Migration("20231225083433_UpdateTypographicResourceLocation")]
    partial class UpdateTypographicResourceLocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.Accountant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Accountants");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.AccountantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("AccountantGroups");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.AccountantSignGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("AccountantSignGroups");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.GroupAccountant", b =>
                {
                    b.Property<int>("AccountantGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountantGroupId", "AccountantId");

                    b.HasIndex("AccountantId");

                    b.ToTable("GroupAccountants");
                });

            modelBuilder.Entity("DBEntities.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("DBEntities.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLocate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("DBEntities.Entities.CustomerModels.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLocate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DBEntities.Entities.CustomerModels.CustomerSealGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuarterYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("TypographyType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterYearId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("CustomerSealGroups");
                });

            modelBuilder.Entity("DBEntities.Entities.ImageRangeModels.ImageRangeLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageRangeSettingId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSealType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImageRangeSettingId");

                    b.ToTable("ImageRangeLocations");
                });

            modelBuilder.Entity("DBEntities.Entities.ImageRangeModels.ImageRangeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("ImageRangeSettings");
                });

            modelBuilder.Entity("DBEntities.Entities.Letterhead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Letterheads");
                });

            modelBuilder.Entity("DBEntities.Entities.QuarterYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GregorianYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("QuarterYears");
                });

            modelBuilder.Entity("DBEntities.Entities.TemplateModels.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageViewFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StackMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StackShift")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("DBEntities.Entities.TemplateModels.TemplateLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateLocations");
                });

            modelBuilder.Entity("DBEntities.Entities.TemplateModels.TemporarySealGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuarterYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterYearId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("TemporarySealGroups");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuarterYearId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<byte>("TypographyType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("QuarterYearId");

                    b.HasIndex("UpdateUserId");

                    b.HasIndex("UploadFileId");

                    b.ToTable("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlankCheck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteCheck")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographicPDFId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UploadFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPDFId");

                    b.HasIndex("UploadFileId");

                    b.ToTable("TypographicPages");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountantSignGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerSealGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LetterheadId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SealType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSealType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemporarySealGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UploadFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignGroupId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("CustomerSealGroupId");

                    b.HasIndex("LetterheadId");

                    b.HasIndex("TemporarySealGroupId");

                    b.HasIndex("UpdateUserId");

                    b.HasIndex("UploadFileId");

                    b.ToTable("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicResourceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Angle")
                        .HasColumnType("REAL");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsInpaint")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<byte?>("SealDyeing")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographicResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPageId");

                    b.HasIndex("TypographicResourceId");

                    b.ToTable("TypographicResourceLocations");
                });

            modelBuilder.Entity("DBEntities.Entities.UploadFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileWorkStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("UploadType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreateUserId");

                    b.HasIndex("UpdateUserId");

                    b.ToTable("UploadFiles");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.Accountant", b =>
                {
                    b.HasOne("DBEntities.Entities.Company", "Company")
                        .WithMany("Accountants")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("AccountantCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("AccountantUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Company");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.AccountantGroup", b =>
                {
                    b.HasOne("DBEntities.Entities.Company", "Company")
                        .WithMany("AccountantGroups")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("AccountantGroupCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("AccountantGroupUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Company");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.AccountantSignGroup", b =>
                {
                    b.HasOne("DBEntities.Entities.AccountantModels.Accountant", "Accountant")
                        .WithMany("AccountantSignGroups")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("AccountantSignGroupCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("AccountantSignGroupUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Accountant");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.GroupAccountant", b =>
                {
                    b.HasOne("DBEntities.Entities.AccountantModels.AccountantGroup", "AccountantGroup")
                        .WithMany("GroupAccountants")
                        .HasForeignKey("AccountantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.AccountantModels.Accountant", "Accountant")
                        .WithMany("GroupAccountants")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");

                    b.Navigation("AccountantGroup");
                });

            modelBuilder.Entity("DBEntities.Entities.ApplicationUser", b =>
                {
                    b.HasOne("DBEntities.Entities.Company", "Company")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("CompanyId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("CreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("UpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Company");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.Company", b =>
                {
                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("CompanyCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("CompanyUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.CustomerModels.Customer", b =>
                {
                    b.HasOne("DBEntities.Entities.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("CustomerCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("CustomerUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Company");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.CustomerModels.CustomerSealGroup", b =>
                {
                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("CustomerSealGroupCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.CustomerModels.Customer", "Customer")
                        .WithMany("CustomerSealGroups")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.QuarterYear", "QuarterYear")
                        .WithMany("CustomerSealGroups")
                        .HasForeignKey("QuarterYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("CustomerSealGroupUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("CreateUser");

                    b.Navigation("Customer");

                    b.Navigation("QuarterYear");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.ImageRangeModels.ImageRangeLocation", b =>
                {
                    b.HasOne("DBEntities.Entities.ImageRangeModels.ImageRangeSetting", "ImageRangeSetting")
                        .WithMany("ImageRangeLocations")
                        .HasForeignKey("ImageRangeSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageRangeSetting");
                });

            modelBuilder.Entity("DBEntities.Entities.ImageRangeModels.ImageRangeSetting", b =>
                {
                    b.HasOne("DBEntities.Entities.Company", "Company")
                        .WithMany("ImageRangeSettings")
                        .HasForeignKey("CompanyId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("ImageRangeSettingCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("ImageRangeSettingUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Company");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.Letterhead", b =>
                {
                    b.HasOne("DBEntities.Entities.Company", "Company")
                        .WithMany("Letterheads")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("LetterheadCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("LetterheadUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Company");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.QuarterYear", b =>
                {
                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany()
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.TemplateModels.Template", b =>
                {
                    b.HasOne("DBEntities.Entities.Company", "Company")
                        .WithMany("Templates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("TemplateCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("TemplateUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Company");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.TemplateModels.TemplateLocation", b =>
                {
                    b.HasOne("DBEntities.Entities.TemplateModels.Template", "Template")
                        .WithMany("TemplateLocations")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("DBEntities.Entities.TemplateModels.TemporarySealGroup", b =>
                {
                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("TemporarySealGroupCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.CustomerModels.Customer", "Customer")
                        .WithMany("TemporarySealGroups")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.QuarterYear", "QuarterYear")
                        .WithMany("TemporarySealGroups")
                        .HasForeignKey("QuarterYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("TemporarySealGroupUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("CreateUser");

                    b.Navigation("Customer");

                    b.Navigation("QuarterYear");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicPDF", b =>
                {
                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("TypographicPDFCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.CustomerModels.Customer", "Customer")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.QuarterYear", "QuarterYear")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("QuarterYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("TypographicPDFUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.HasOne("DBEntities.Entities.UploadFile", "UploadFile")
                        .WithMany("TypographicPDFs")
                        .HasForeignKey("UploadFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateUser");

                    b.Navigation("Customer");

                    b.Navigation("QuarterYear");

                    b.Navigation("UpdateUser");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicPage", b =>
                {
                    b.HasOne("DBEntities.Entities.TypographicModels.TypographicPDF", "TypographicPDF")
                        .WithMany("TypographicPages")
                        .HasForeignKey("TypographicPDFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.UploadFile", "UploadFile")
                        .WithMany()
                        .HasForeignKey("UploadFileId");

                    b.Navigation("TypographicPDF");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicResource", b =>
                {
                    b.HasOne("DBEntities.Entities.AccountantModels.AccountantSignGroup", "AccountantSignGroup")
                        .WithMany("TypographicResources")
                        .HasForeignKey("AccountantSignGroupId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("TypographicResourceCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.CustomerModels.CustomerSealGroup", "CustomerSealGroup")
                        .WithMany("TypographicResources")
                        .HasForeignKey("CustomerSealGroupId");

                    b.HasOne("DBEntities.Entities.Letterhead", "Letterhead")
                        .WithMany("TypographicResources")
                        .HasForeignKey("LetterheadId");

                    b.HasOne("DBEntities.Entities.TemplateModels.TemporarySealGroup", "TemporarySealGroup")
                        .WithMany("TypographicResources")
                        .HasForeignKey("TemporarySealGroupId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("TypographicResourceUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.HasOne("DBEntities.Entities.UploadFile", "UploadFile")
                        .WithMany("TypographicResources")
                        .HasForeignKey("UploadFileId");

                    b.Navigation("AccountantSignGroup");

                    b.Navigation("CreateUser");

                    b.Navigation("CustomerSealGroup");

                    b.Navigation("Letterhead");

                    b.Navigation("TemporarySealGroup");

                    b.Navigation("UpdateUser");

                    b.Navigation("UploadFile");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicResourceLocation", b =>
                {
                    b.HasOne("DBEntities.Entities.TypographicModels.TypographicPage", "TypographicPage")
                        .WithMany("TypographicResourceLocations")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.TypographicModels.TypographicResource", "TypographicResource")
                        .WithMany("TypographicResourceLocations")
                        .HasForeignKey("TypographicResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypographicPage");

                    b.Navigation("TypographicResource");
                });

            modelBuilder.Entity("DBEntities.Entities.UploadFile", b =>
                {
                    b.HasOne("DBEntities.Entities.Company", "Company")
                        .WithMany("UploadFiles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Entities.ApplicationUser", "CreateUser")
                        .WithMany("UploadFileCreateUsers")
                        .HasForeignKey("CreateUserId");

                    b.HasOne("DBEntities.Entities.ApplicationUser", "UpdateUser")
                        .WithMany("UploadFileUpdateUsers")
                        .HasForeignKey("UpdateUserId");

                    b.Navigation("Company");

                    b.Navigation("CreateUser");

                    b.Navigation("UpdateUser");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.Accountant", b =>
                {
                    b.Navigation("AccountantSignGroups");

                    b.Navigation("GroupAccountants");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.AccountantGroup", b =>
                {
                    b.Navigation("GroupAccountants");
                });

            modelBuilder.Entity("DBEntities.Entities.AccountantModels.AccountantSignGroup", b =>
                {
                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AccountantCreateUsers");

                    b.Navigation("AccountantGroupCreateUsers");

                    b.Navigation("AccountantGroupUpdateUsers");

                    b.Navigation("AccountantSignGroupCreateUsers");

                    b.Navigation("AccountantSignGroupUpdateUsers");

                    b.Navigation("AccountantUpdateUsers");

                    b.Navigation("CompanyCreateUsers");

                    b.Navigation("CompanyUpdateUsers");

                    b.Navigation("CreateUsers");

                    b.Navigation("CustomerCreateUsers");

                    b.Navigation("CustomerSealGroupCreateUsers");

                    b.Navigation("CustomerSealGroupUpdateUsers");

                    b.Navigation("CustomerUpdateUsers");

                    b.Navigation("ImageRangeSettingCreateUsers");

                    b.Navigation("ImageRangeSettingUpdateUsers");

                    b.Navigation("LetterheadCreateUsers");

                    b.Navigation("LetterheadUpdateUsers");

                    b.Navigation("TemplateCreateUsers");

                    b.Navigation("TemplateUpdateUsers");

                    b.Navigation("TemporarySealGroupCreateUsers");

                    b.Navigation("TemporarySealGroupUpdateUsers");

                    b.Navigation("TypographicPDFCreateUsers");

                    b.Navigation("TypographicPDFUpdateUsers");

                    b.Navigation("TypographicResourceCreateUsers");

                    b.Navigation("TypographicResourceUpdateUsers");

                    b.Navigation("UpdateUsers");

                    b.Navigation("UploadFileCreateUsers");

                    b.Navigation("UploadFileUpdateUsers");
                });

            modelBuilder.Entity("DBEntities.Entities.Company", b =>
                {
                    b.Navigation("AccountantGroups");

                    b.Navigation("Accountants");

                    b.Navigation("ApplicationUsers");

                    b.Navigation("Customers");

                    b.Navigation("ImageRangeSettings");

                    b.Navigation("Letterheads");

                    b.Navigation("Templates");

                    b.Navigation("UploadFiles");
                });

            modelBuilder.Entity("DBEntities.Entities.CustomerModels.Customer", b =>
                {
                    b.Navigation("CustomerSealGroups");

                    b.Navigation("TemporarySealGroups");

                    b.Navigation("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntities.Entities.CustomerModels.CustomerSealGroup", b =>
                {
                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.Entities.ImageRangeModels.ImageRangeSetting", b =>
                {
                    b.Navigation("ImageRangeLocations");
                });

            modelBuilder.Entity("DBEntities.Entities.Letterhead", b =>
                {
                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.Entities.QuarterYear", b =>
                {
                    b.Navigation("CustomerSealGroups");

                    b.Navigation("TemporarySealGroups");

                    b.Navigation("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntities.Entities.TemplateModels.Template", b =>
                {
                    b.Navigation("TemplateLocations");
                });

            modelBuilder.Entity("DBEntities.Entities.TemplateModels.TemporarySealGroup", b =>
                {
                    b.Navigation("TypographicResources");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicPDF", b =>
                {
                    b.Navigation("TypographicPages");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicPage", b =>
                {
                    b.Navigation("TypographicResourceLocations");
                });

            modelBuilder.Entity("DBEntities.Entities.TypographicModels.TypographicResource", b =>
                {
                    b.Navigation("TypographicResourceLocations");
                });

            modelBuilder.Entity("DBEntities.Entities.UploadFile", b =>
                {
                    b.Navigation("TypographicPDFs");

                    b.Navigation("TypographicResources");
                });
#pragma warning restore 612, 618
        }
    }
}
