// <auto-generated />
using System;
using DBEntities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Sqlite.Migrations
{
    [DbContext(typeof(SealTypographicDbContext))]
    [Migration("20230411100724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("DBEntities.AccountSignSealTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageViewFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("AccountSignSealTemplates");
                });

            modelBuilder.Entity("DBEntities.AccountSignSealTemplateLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountSignSealTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountSignSealTemplateId");

                    b.ToTable("AccountSignSealTemplateLocations");
                });

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantGroupId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Accountants");
                });

            modelBuilder.Entity("DBEntities.AccountantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountantGroupNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccountantGroups");
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroupJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantId");

                    b.ToTable("AccountantSignGroupJournals");
                });

            modelBuilder.Entity("DBEntities.AccountantSignJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantSignGroupJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignGroupJournalId");

                    b.ToTable("AccountantSignJournals");
                });

            modelBuilder.Entity("DBEntities.AccountantSignLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountantSignJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountantSignJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("AccountantSignLocaltions");
                });

            modelBuilder.Entity("DBEntities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("DBEntities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressArea")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLocate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTelephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("President")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DBEntities.CustomerSealJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerSealQuarterJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSealQuarterJournalId");

                    b.ToTable("CustomerSealJournals");
                });

            modelBuilder.Entity("DBEntities.CustomerSealLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerSealJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSealJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("CustomerSealLocaltions");
                });

            modelBuilder.Entity("DBEntities.CustomerSealQuarterJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<sbyte>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerSealQuarterJournals");
                });

            modelBuilder.Entity("DBEntities.CustomerSealTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageViewFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StackMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StackShift")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CustomerSealTemplates");
                });

            modelBuilder.Entity("DBEntities.CustomerSealTemplateLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTemplateId");

                    b.ToTable("CustomerSealTemplateLocations");
                });

            modelBuilder.Entity("DBEntities.Letterhead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Letterheads");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LetterheadId")
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LetterheadId");

                    b.ToTable("LetterheadImageJournals");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<int>("LetterheadImageJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LetterheadImageJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("LetterheadImageLocaltions");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageViewFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperOrientation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("LetterheadImageTemplates");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageTemplateLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTemplateId");

                    b.ToTable("LetterheadImageTemplateLocations");
                });

            modelBuilder.Entity("DBEntities.TemporarySealJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemporarySealQuarterJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailFullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemporarySealQuarterJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("TemporarySealJournals");
                });

            modelBuilder.Entity("DBEntities.TemporarySealLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Left")
                        .HasColumnType("REAL");

                    b.Property<int>("TemporarySealJournalId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Top")
                        .HasColumnType("REAL");

                    b.Property<int>("TypographicPageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TemporarySealJournalId");

                    b.HasIndex("TypographicPageId");

                    b.ToTable("TemporarySealLocation");
                });

            modelBuilder.Entity("DBEntities.TemporarySealQuarterJournal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TemporarySealQuarterJournals");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TypographicPDFs");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypographicPDFId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypographicPDFId");

                    b.ToTable("TypographicPages");
                });

            modelBuilder.Entity("DBEntities.UploadFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("DeleteStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileWorkStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdateUserId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("UploadType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("UploadFiles");
                });

            modelBuilder.Entity("DBEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pwaosrsd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DBEntities.AccountSignSealTemplate", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("AccountSignSealTemplates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.AccountSignSealTemplateLocation", b =>
                {
                    b.HasOne("DBEntities.AccountSignSealTemplate", "AccountSignSealTemplate")
                        .WithMany("AccountSignSealTemplateLocations")
                        .HasForeignKey("AccountSignSealTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountSignSealTemplate");
                });

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.HasOne("DBEntities.AccountantGroup", "AccountantGroup")
                        .WithMany("Accountants")
                        .HasForeignKey("AccountantGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Accountants")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantGroup");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroupJournal", b =>
                {
                    b.HasOne("DBEntities.Accountant", "Accountant")
                        .WithMany("AccountantSignGroupJournals")
                        .HasForeignKey("AccountantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accountant");
                });

            modelBuilder.Entity("DBEntities.AccountantSignJournal", b =>
                {
                    b.HasOne("DBEntities.AccountantSignGroupJournal", "AccountantSignGroupJournal")
                        .WithMany("AccountantSignJournals")
                        .HasForeignKey("AccountantSignGroupJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantSignGroupJournal");
                });

            modelBuilder.Entity("DBEntities.AccountantSignLocation", b =>
                {
                    b.HasOne("DBEntities.AccountantSignJournal", "AccountantSignJournal")
                        .WithMany("AccountantSignLocations")
                        .HasForeignKey("AccountantSignJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicPage", "TypographicPage")
                        .WithMany("AccountantSignLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountantSignJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("DBEntities.Customer", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.CustomerSealJournal", b =>
                {
                    b.HasOne("DBEntities.CustomerSealQuarterJournal", "CustomerSealQuarterJournal")
                        .WithMany("CustomerSealJournals")
                        .HasForeignKey("CustomerSealQuarterJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerSealQuarterJournal");
                });

            modelBuilder.Entity("DBEntities.CustomerSealLocation", b =>
                {
                    b.HasOne("DBEntities.CustomerSealJournal", "CustomerSealJournal")
                        .WithMany("CustomerSealLocations")
                        .HasForeignKey("CustomerSealJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicPage", "TypographicPage")
                        .WithMany("CustomerSealLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerSealJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("DBEntities.CustomerSealQuarterJournal", b =>
                {
                    b.HasOne("DBEntities.Customer", "Customer")
                        .WithMany("CustomerSealQuarterJournals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DBEntities.CustomerSealTemplate", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("CustomerSealTemplates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.CustomerSealTemplateLocation", b =>
                {
                    b.HasOne("DBEntities.CustomerSealTemplate", "CustomerTemplate")
                        .WithMany("CustomerTempTemplateLocations")
                        .HasForeignKey("CustomerTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerTemplate");
                });

            modelBuilder.Entity("DBEntities.Letterhead", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Letterheads")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageJournal", b =>
                {
                    b.HasOne("DBEntities.Letterhead", "Letterhead")
                        .WithMany("LetterheadImageJournals")
                        .HasForeignKey("LetterheadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Letterhead");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageLocation", b =>
                {
                    b.HasOne("DBEntities.LetterheadImageJournal", "LetterheadImageJournal")
                        .WithMany("LetterheadImageLocations")
                        .HasForeignKey("LetterheadImageJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicPage", "TypographicPage")
                        .WithMany("LetterheadImageLocaltions")
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LetterheadImageJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageTemplate", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("LetterheadImageTemplates")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageTemplateLocation", b =>
                {
                    b.HasOne("DBEntities.LetterheadImageTemplate", "CustomerTemplate")
                        .WithMany("LetterheadImageTemplateLocations")
                        .HasForeignKey("CustomerTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerTemplate");
                });

            modelBuilder.Entity("DBEntities.TemporarySealJournal", b =>
                {
                    b.HasOne("DBEntities.TemporarySealQuarterJournal", "TemporarySealQuarterJournal")
                        .WithMany("TemporarySealJournals")
                        .HasForeignKey("TemporarySealQuarterJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicPage", null)
                        .WithMany("TemporarySealJournals")
                        .HasForeignKey("TypographicPageId");

                    b.Navigation("TemporarySealQuarterJournal");
                });

            modelBuilder.Entity("DBEntities.TemporarySealLocation", b =>
                {
                    b.HasOne("DBEntities.TemporarySealJournal", "TemporarySealJournal")
                        .WithMany("TemporarySealLocations")
                        .HasForeignKey("TemporarySealJournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBEntities.TypographicPage", "TypographicPage")
                        .WithMany()
                        .HasForeignKey("TypographicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemporarySealJournal");

                    b.Navigation("TypographicPage");
                });

            modelBuilder.Entity("DBEntities.TemporarySealQuarterJournal", b =>
                {
                    b.HasOne("DBEntities.Customer", "Customer")
                        .WithMany("TemporarySealQuarterJournals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.HasOne("DBEntities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.HasOne("DBEntities.TypographicPDF", "TypographicPDF")
                        .WithMany("TypographicPages")
                        .HasForeignKey("TypographicPDFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypographicPDF");
                });

            modelBuilder.Entity("DBEntities.UploadFile", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("UploadFiles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.User", b =>
                {
                    b.HasOne("DBEntities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DBEntities.AccountSignSealTemplate", b =>
                {
                    b.Navigation("AccountSignSealTemplateLocations");
                });

            modelBuilder.Entity("DBEntities.Accountant", b =>
                {
                    b.Navigation("AccountantSignGroupJournals");
                });

            modelBuilder.Entity("DBEntities.AccountantGroup", b =>
                {
                    b.Navigation("Accountants");
                });

            modelBuilder.Entity("DBEntities.AccountantSignGroupJournal", b =>
                {
                    b.Navigation("AccountantSignJournals");
                });

            modelBuilder.Entity("DBEntities.AccountantSignJournal", b =>
                {
                    b.Navigation("AccountantSignLocations");
                });

            modelBuilder.Entity("DBEntities.Company", b =>
                {
                    b.Navigation("AccountSignSealTemplates");

                    b.Navigation("Accountants");

                    b.Navigation("CustomerSealTemplates");

                    b.Navigation("Customers");

                    b.Navigation("LetterheadImageTemplates");

                    b.Navigation("Letterheads");

                    b.Navigation("UploadFiles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DBEntities.Customer", b =>
                {
                    b.Navigation("CustomerSealQuarterJournals");

                    b.Navigation("TemporarySealQuarterJournals");
                });

            modelBuilder.Entity("DBEntities.CustomerSealJournal", b =>
                {
                    b.Navigation("CustomerSealLocations");
                });

            modelBuilder.Entity("DBEntities.CustomerSealQuarterJournal", b =>
                {
                    b.Navigation("CustomerSealJournals");
                });

            modelBuilder.Entity("DBEntities.CustomerSealTemplate", b =>
                {
                    b.Navigation("CustomerTempTemplateLocations");
                });

            modelBuilder.Entity("DBEntities.Letterhead", b =>
                {
                    b.Navigation("LetterheadImageJournals");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageJournal", b =>
                {
                    b.Navigation("LetterheadImageLocations");
                });

            modelBuilder.Entity("DBEntities.LetterheadImageTemplate", b =>
                {
                    b.Navigation("LetterheadImageTemplateLocations");
                });

            modelBuilder.Entity("DBEntities.TemporarySealJournal", b =>
                {
                    b.Navigation("TemporarySealLocations");
                });

            modelBuilder.Entity("DBEntities.TemporarySealQuarterJournal", b =>
                {
                    b.Navigation("TemporarySealJournals");
                });

            modelBuilder.Entity("DBEntities.TypographicPDF", b =>
                {
                    b.Navigation("TypographicPages");
                });

            modelBuilder.Entity("DBEntities.TypographicPage", b =>
                {
                    b.Navigation("AccountantSignLocaltions");

                    b.Navigation("CustomerSealLocaltions");

                    b.Navigation("LetterheadImageLocaltions");

                    b.Navigation("TemporarySealJournals");
                });
#pragma warning restore 612, 618
        }
    }
}
