<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="license.elic.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="license.elic.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DJImageLib" Version="1.0.1" />
    <PackageReference Include="Spire.Office" Version="8.11.0" />
    <PackageReference Include="Spire.PDF" Version="9.11.4" />
    <PackageReference Include="Spire.XLS" Version="13.10.1" />
  </ItemGroup>

</Project>
