<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Library\**" />
    <EmbeddedResource Remove="Library\**" />
    <None Remove="Library\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spire.PDF" Version="9.5.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="license.elic.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="license.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
