[PrivateArguments]
ReferenceViewRatioFlag=1
;驗印鬆緊度
ComparisonLevel=1
;攝影機名稱:麥哲-Document Scanner,良田-S1800,S1500A3AF
VideoDeviceName=S1800
;攝影機實際DPI(配合解析度修改)
VideoHorzDPI=250
VideoVertDPI=253
;預覽水平解析度
VideoHorzRes=3264
;預覽垂直解析度
VideoVertRes=2448
;拍攝解析度 X × Y
CaptureHorzRes=3264
CaptureVertRes=2448
;拍攝式，切換解析度等待時間(1sec=1000)
VideoResChangeTime=8000
;亮度值/0:自動，1:手動
Bright=0,1
;對比度/0:自動，1:手動
Contrast=48,1
;色調值/0:自動，1:手動
Hue=0,1
;飽和度/0:自動，1:手動
Saturation=100,1
;清晰度/0:自動，1:手動
Sharpness=8,1
;色差補正/0:自動，1:手動
Gamma=405,1
;白平衡/0:自動，1:手動
WB=6220,0
;背光補償/0:自動，1:手動
BLC=0,1
;增益/0:自動，1:手動
Gain=0,1
;啟用色彩/0:啟用，1:不啟用
ColorEnable=1
;縮放/0:自動，1:手動
Zoom=0,1
;焦距值/0:自動，1:手動
Focus=0,1
;曝光值/0:自動，1:手動
Exposure=-4,0
;光圈/0:自動，1:手動
Iris=-0,1
;取景位置調整/0:自動，1:手動
Pan=0,1
;傾斜/0:自動，1:手動
Tilt=0,1
;捲動速度/0:自動，1:手動
Roll=0,1
;啟用弱光補償/0:啟用，1:不啟用(暫無設定值)
LLC=-3,1
;目視比對1:1 水平ratio
SealScaleX=0.304
;目視比對1:1 垂直ratio
SealScaleY=0.308
;拍攝比對1:1 水平ratio
VideoScaleX=0.838
;拍攝比對1:1 垂直ratio
VideoScaleY=0.847
;reaConverter自動白平衡，0:啟用，1:不啟用
reaConverterWB=0
;是否啟用尋邊功能，0:啟用，1:不啟用
Deskew=1
;遮罩擷取 X 座標
Mask_Capture_Region_X=667
;遮罩擷取 Y 座標
Mask_Capture_Region_Y=296
;遮罩擷取 W 寬度
Mask_Capture_Region_W=2561
;遮罩擷取 H 高度
Mask_Capture_Region_H=1711
;相機畫面是旋轉 (0:不旋轉 1:右旋轉90 2:右旋轉180 3:右旋轉270)
VideoPreviewRotateType=0
BankComparsionSplitKeyValue=0
LandComparsionSplitKeyValue=0
OnlineService_CapturePort=6100
CloseDeleteFile=N
;印鑑卡擷取 X 座標
SealCard_Capture_Region_X=41.25675
;印鑑卡擷取 Y 座標
SealCard_Capture_Region_Y=64.6937
;印鑑卡擷取 W 寬度
SealCard_Capture_Region_W=669.5045
;印鑑卡擷取 H 高度
SealCard_Capture_Region_H=370.1081
;打開/關閉 印鑑卡驗印擷取範圍
OpenSealCardRegion=N
;OpenSummonsRegion=N
HandAngleImageAngle=0
HandComparsionType=0
HandComparsionScaleValue=0
HandComparsionSpeedValue=1
HandComparsionOpacityValue=1
AutoAfterImageSpeed=5
AutoAngleImageSpeed=5
AutoPerspectiveImageSpeed=5
AutoAngleImageAngle=45
SuperPictureBox_Brightness=0
SuperPictureBox_Contrast=0
SuperPictureBox_Sharpen=0
SuperPictureBox_Scale=0
SuperPictureBox_Rotate=0
;傳票正面擷取 X 座標
Summons_Capture_F_Region_X=1196.403
;傳票正面擷取 Y 座標
Summons_Capture_F_Region_Y=571.2208
;傳票正面擷取 W 寬度
Summons_Capture_F_Region_W=915.0361
;傳票正面擷取 H 高度
Summons_Capture_F_Region_H=527.9054
;傳票背面擷取 X 座標
Summons_Capture_R_Region_X=73.97634
;傳票背面擷取 Y 座標
Summons_Capture_R_Region_Y=54.68919
;傳票背面擷取 W 寬度
Summons_Capture_R_Region_W=775.723
;傳票背面擷取 H 高度
Summons_Capture_R_Region_H=518.1081
OpenSummons_F_Region=N
OpenSummons_R_Region=N
LandComparisonSplitKeyValue=0
BankComparisonSplitKeyValue=0
HandComparisonType=0
HandComparisonScaleValue=0
HandComparisonSpeedValue=1
HandComparisonOpacityValue=1
